import "dotenv/config";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

// Royalty-free Unsplash farm/land images
const FARM_IMAGES = [
  "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1464226184884-fa280b87c399?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1416879595882-3373a0480b5b?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1625246333195-78d9c38ad449?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1560493676-04071c5f467b?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1589923188651-268a9765e432?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1523348837708-15d4a09cfac2?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1504433374832-4fcf45f40967?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1602941525421-8f8b81d3edbb?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1444858291040-58f756a3bdd6?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1549773604-12eed0a86da3?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1570913149827-d2ac84ab3f9a?w=800&q=80&auto=format&fit=crop",
  "https://images.unsplash.com/photo-1596701062351-8c2c14d1fdd0?w=800&q=80&auto=format&fit=crop",
];

const listings = [
  {
    title: "5 Acre Fertile Agricultural Land in Padra, Vadodara",
    description: "Prime agricultural land suitable for cotton, wheat, and vegetable cultivation. Well-irrigated with canal water access. Situated on SH-64 highway, just 18 km from Vadodara city. Survey No. 142/B. Clean 7/12 extract available.",
    city: "Vadodara",
    taluka: "Padra",
    village: "Vadadla",
    landType: "AGRICULTURAL" as const,
    areaValue: 5,
    areaUnit: "ACRE" as const,
    priceTotal: 4500000,
    pricePerUnit: 900000,
    roadAccess: true,
    waterSource: "Canal + Bore Well",
    ownerName: "Rameshbhai Patel",
    ownerPhone: "9825041234",
    ownerEmail: "rpatel@gmail.com",
    featured: true,
    verified: true,
    images: [FARM_IMAGES[0], FARM_IMAGES[3]],
  },
  {
    title: "12 Bigha Agricultural Land Near Anand — Ideal for Dairy Farming",
    description: "Flat, level land with excellent connectivity. Adjacent to main road from Anand to Borsad. Canal irrigation rights included. Perfect for dairy farm or organic farming. All legal documents ready.",
    city: "Anand",
    taluka: "Borsad",
    village: "Umreth",
    landType: "AGRICULTURAL" as const,
    areaValue: 12,
    areaUnit: "BIGHA" as const,
    priceTotal: 7200000,
    pricePerUnit: 600000,
    roadAccess: true,
    waterSource: "Canal Irrigation",
    ownerName: "Sureshbhai Desai",
    ownerPhone: "9978123456",
    featured: true,
    verified: true,
    images: [FARM_IMAGES[1], FARM_IMAGES[4]],
  },
  {
    title: "NA Residential Plot — 2000 Sq Ft in Gotri, Vadodara",
    description: "Non-Agricultural plot in prime Gotri locality near BAPS Swaminarayan temple. Fully developed area with water, drainage, and electricity connections. Perfect for individual bungalow or duplex construction. TP Scheme approved.",
    city: "Vadodara",
    taluka: "Vadodara",
    village: "Gotri",
    landType: "NA_RESIDENTIAL" as const,
    areaValue: 2000,
    areaUnit: "SQ_FT" as const,
    priceTotal: 3800000,
    pricePerUnit: 1900,
    roadAccess: true,
    waterSource: "Municipal Supply",
    ownerName: "Nileshbhai Shah",
    ownerPhone: "9824567890",
    featured: true,
    verified: false,
    images: [FARM_IMAGES[2]],
  },
  {
    title: "8 Acre Mango Orchard Land in Bharuch — Near NH-48",
    description: "Established mango orchard on 8 acres. 250+ mature Kesar & Alphonso trees in productive age. Property has permanent bore well, storage shed, and a small caretaker room. On pucca road just off NH-48.",
    city: "Bharuch",
    taluka: "Amod",
    village: "Devsar",
    landType: "FARM_HOUSE" as const,
    areaValue: 8,
    areaUnit: "ACRE" as const,
    priceTotal: 9600000,
    pricePerUnit: 1200000,
    roadAccess: true,
    waterSource: "Bore Well",
    ownerName: "Hasmukhlal Prajapati",
    ownerPhone: "9898234567",
    featured: false,
    verified: true,
    images: [FARM_IMAGES[5], FARM_IMAGES[8]],
  },
  {
    title: "Industrial Plot — 5000 Sq Mt in Panoli GIDC, Bharuch",
    description: "Ready NA-Industrial plot in Panoli GIDC notified area. Suitable for chemical, pharma, or manufacturing unit. Three-phase power connection available. 24m wide road frontage. Clear title.",
    city: "Bharuch",
    taluka: "Ankleshwar",
    village: "Panoli",
    landType: "INDUSTRIAL" as const,
    areaValue: 5000,
    areaUnit: "SQ_METER" as const,
    priceTotal: 15000000,
    pricePerUnit: 3000,
    roadAccess: true,
    waterSource: "GIDC Water Supply",
    ownerName: "Pravinbhai Mehta",
    ownerPhone: "9737456789",
    featured: false,
    verified: false,
    images: [FARM_IMAGES[6]],
  },
  {
    title: "3 Bigha Agricultural Land in Matar Taluka, Nadiad",
    description: "Good quality black soil land ideal for groundnut and sugarcane. Electricity connection available on the plot. Located 5 km from Matar town on all-weather road. Survey No. 456/A.",
    city: "Nadiad",
    taluka: "Matar",
    village: "Bhadran",
    landType: "AGRICULTURAL" as const,
    areaValue: 3,
    areaUnit: "BIGHA" as const,
    priceTotal: 1800000,
    pricePerUnit: 600000,
    roadAccess: true,
    waterSource: "Bore Well",
    ownerName: "Dahyabhai Chauhan",
    ownerPhone: "9662098765",
    featured: false,
    verified: false,
    images: [FARM_IMAGES[7]],
  },
  {
    title: "Commercial NA Plot — 4500 Sq Ft on SG Highway, Ahmedabad",
    description: "Premium corner commercial plot on SG Highway frontage near Bopal junction. Surrounded by established commercial complexes, showrooms, and offices. Exceptional visibility and footfall. Immediate possession.",
    city: "Ahmedabad",
    taluka: "Daskroi",
    village: "Bopal",
    landType: "NA_COMMERCIAL" as const,
    areaValue: 4500,
    areaUnit: "SQ_FT" as const,
    priceTotal: 22500000,
    pricePerUnit: 5000,
    roadAccess: true,
    waterSource: "Municipal Supply",
    ownerName: "Alpeshbhai Modi",
    ownerPhone: "9824011122",
    featured: true,
    verified: true,
    images: [FARM_IMAGES[9], FARM_IMAGES[12]],
  },
  {
    title: "20 Acre Agricultural Land in Viramgam, Ahmedabad",
    description: "Vast agricultural holding suitable for large-scale cultivation or poultry/dairy setup. Narmada canal water available for irrigation. Located near Viramgam GIDC. Flexible payment terms available.",
    city: "Ahmedabad",
    taluka: "Viramgam",
    village: "Nandol",
    landType: "AGRICULTURAL" as const,
    areaValue: 20,
    areaUnit: "ACRE" as const,
    priceTotal: 16000000,
    pricePerUnit: 800000,
    roadAccess: false,
    waterSource: "Narmada Canal",
    ownerName: "Bhaveshbhai Thakkar",
    ownerPhone: "9099876543",
    featured: false,
    verified: false,
    images: [FARM_IMAGES[10]],
  },
  {
    title: "Farm House Plot — 4 Acre with Well in Olpad, Surat",
    description: "Scenic plot ideal for a weekend farm house. Lush green surroundings, very close to Tapi river belt. Existing small kaccha house and a step-well on property. Road accessible from Olpad-Kamrej highway.",
    city: "Surat",
    taluka: "Olpad",
    village: "Kholvad",
    landType: "FARM_HOUSE" as const,
    areaValue: 4,
    areaUnit: "ACRE" as const,
    priceTotal: 5600000,
    pricePerUnit: 1400000,
    roadAccess: true,
    waterSource: "Step Well + Bore Well",
    ownerName: "Dineshbhai Gamit",
    ownerPhone: "9725331234",
    featured: false,
    verified: true,
    images: [FARM_IMAGES[11], FARM_IMAGES[3]],
  },
  {
    title: "Residential Plot — 1500 Sq Ft in Kamrej, Surat",
    description: "Approved layout plot in fast-developing Kamrej area. Ready for immediate construction. Water, electricity connections at plot boundary. 10 min drive from Surat international airport. Zero FSI issues.",
    city: "Surat",
    taluka: "Kamrej",
    village: "Sayan",
    landType: "PLOT" as const,
    areaValue: 1500,
    areaUnit: "SQ_FT" as const,
    priceTotal: 2100000,
    pricePerUnit: 1400,
    roadAccess: true,
    waterSource: "Municipal Supply",
    ownerName: "Jayeshbhai Patel",
    ownerPhone: "9978552233",
    featured: false,
    verified: false,
    images: [FARM_IMAGES[13]],
  },
  {
    title: "7 Bigha Sugarcane Land in Petlad, Anand — Road Touch",
    description: "Productive agricultural land with an excellent track record of sugarcane yield. All Petlad Sugar Co-op society rights transferable to buyer. 2 borewells already drilled. Direct road frontage of 40 feet.",
    city: "Anand",
    taluka: "Petlad",
    village: "Vasna",
    landType: "AGRICULTURAL" as const,
    areaValue: 7,
    areaUnit: "BIGHA" as const,
    priceTotal: 5600000,
    pricePerUnit: 800000,
    roadAccess: true,
    waterSource: "2 Bore Wells",
    ownerName: "Nareshbhai Patel",
    ownerPhone: "9825667788",
    featured: false,
    verified: true,
    images: [FARM_IMAGES[14], FARM_IMAGES[0]],
  },
  {
    title: "30 Guntha NA Land in Dabhoi, Vadodara — Near Champaner Highway",
    description: "Non-Agricultural land on Vadodara-Dabhoi highway. Previously used for warehouse operations. Strong concrete boundary wall on three sides. Power transformer on plot. Price negotiable for quick sale.",
    city: "Vadodara",
    taluka: "Dabhoi",
    village: "Dabhoi",
    landType: "NA_COMMERCIAL" as const,
    areaValue: 30,
    areaUnit: "GUNTHA" as const,
    priceTotal: 6000000,
    pricePerUnit: 200000,
    roadAccess: true,
    waterSource: "Bore Well",
    ownerName: "Kiranbhai Solanki",
    ownerPhone: "9824992211",
    featured: false,
    verified: false,
    images: [FARM_IMAGES[2], FARM_IMAGES[6]],
  },
  {
    title: "10 Hectare Agricultural Land in Jhagadia, Bharuch",
    description: "Large holding suitable for institutional buyer or investment. Fertile Narmada canal-fed land producing 2 crops annually. Clean survey record. Located just 8 km from Jhagadia GIDC, excellent future appreciation potential.",
    city: "Bharuch",
    taluka: "Jhagadia",
    village: "Atali",
    landType: "AGRICULTURAL" as const,
    areaValue: 10,
    areaUnit: "HECTARE" as const,
    priceTotal: 18000000,
    pricePerUnit: 1800000,
    roadAccess: false,
    waterSource: "Narmada Canal",
    ownerName: "Maheshbhai Parmar",
    ownerPhone: "9737001122",
    featured: true,
    verified: false,
    images: [FARM_IMAGES[4], FARM_IMAGES[7]],
  },
  {
    title: "Industrial Plot — 2 Acre in Kapadvanj GIDC, Nadiad",
    description: "Industrial-use land inside Kapadvanj notified GIDC area. Water connection and 3-phase electric supply available at plot boundary. Suitable for light manufacturing, warehousing, or cold storage. All clearances in place.",
    city: "Nadiad",
    taluka: "Kapadvanj",
    village: "Kapadvanj",
    landType: "INDUSTRIAL" as const,
    areaValue: 2,
    areaUnit: "ACRE" as const,
    priceTotal: 7000000,
    pricePerUnit: 3500000,
    roadAccess: true,
    waterSource: "GIDC Supply",
    ownerName: "Rajeshbhai Trivedi",
    ownerPhone: "9099334455",
    featured: false,
    verified: true,
    images: [FARM_IMAGES[9]],
  },
  {
    title: "3000 Sq Ft NA Plot in Bardoli, Surat — Gated Township",
    description: "Corner plot in a new approved township scheme near Bardoli. Fully developed infrastructure: tar roads, underground drainage, LED streetlights. Walking distance to Bardoli college campus. Best for investment or own construction.",
    city: "Surat",
    taluka: "Bardoli",
    village: "Bardoli",
    landType: "PLOT" as const,
    areaValue: 3000,
    areaUnit: "SQ_FT" as const,
    priceTotal: 3600000,
    pricePerUnit: 1200,
    roadAccess: true,
    waterSource: "Municipal Supply",
    ownerName: "Harshadbhai Vasava",
    ownerPhone: "9879001234",
    featured: false,
    verified: false,
    images: [FARM_IMAGES[1], FARM_IMAGES[5]],
  },
];

async function main() {
  console.log("Seeding listings...");

  for (const listing of listings) {
    await prisma.listing.create({
      data: {
        ...listing,
        status: "APPROVED",
      },
    });
    process.stdout.write(".");
  }

  console.log(`\n✓ Seeded ${listings.length} listings`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(() => prisma.$disconnect());
